opam-version: "2.0"
synopsis: "Verified OpenAI-compatible HTTP requests"
maintainer: "Stogas"
authors: "Stogas"
license: "Apache-2.0"
depends: [
  "ocaml" {>= "5.2" & < "6"}
  "dune" {>= "3.16"}
  "ctypes" {= "0.24.0"}
  "ctypes-foreign" {= "0.24.0"}
  "ocurl" {= "0.9.2"}
  "yojson" {>= "2.2" & < "4"}
  "uri" {>= "4.4" & < "5"}
]
build: [["dune" "build" "-p" name "-j" jobs]]
