[package]
name = "stogas-verifier-python"
description = "Python bindings for the Stogas SDK"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
repository.workspace = true

[lib]
name = "_stogas_verifier"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.29.0", features = ["abi3-py310", "extension-module"] }
serde_json.workspace = true
serde.workspace = true
stogas-verifier = { path = "../../crates/verifier" }
stogas-sdk = { package = "stogas", path = "../../crates/cli" }

[lints]
workspace = true
